export interface Job {
  id: number;
  title: string;
  company: string;
  location: string;
  mode: string;
  experience: string;
  skills: string[];
  source: string;
  postedDaysAgo: number;
  salaryRange: string;
  applyUrl: string;
  description: string;
}

export const jobsDataset: Job[] = [
  { id: 1, title: "SDE Intern", company: "Amazon", location: "Bangalore", mode: "Onsite", experience: "Fresher", skills: ["Java", "Data Structures", "Problem Solving"], source: "LinkedIn", postedDaysAgo: 1, salaryRange: "₹20k–₹30k/month Internship", applyUrl: "https://amazon.jobs/en/jobs/123456", description: "Amazon is looking for talented engineering interns to join our Bangalore office. Work on scalable systems and real-world problems. You'll mentor with senior engineers and contribute to production systems. Located in Whitefield, close to tech hubs." },
  { id: 2, title: "Graduate Engineer Trainee", company: "Infosys", location: "Pune", mode: "Onsite", experience: "Fresher", skills: ["C++", "Java", "SQL"], source: "Naukri", postedDaysAgo: 2, salaryRange: "3–5 LPA", applyUrl: "https://naukri.com/job-1234", description: "Infosys Pune is hiring fresh graduates for our Global Infotech Engineer (GIE) program. 6-month training period followed by project assignment. Excellent learning curve with industry experts. Located in Hinjewadi IT Park." },
  { id: 3, title: "Junior Backend Developer", company: "Flipkart", location: "Bangalore", mode: "Hybrid", experience: "0-1", skills: ["Python", "Django", "PostgreSQL", "REST APIs"], source: "LinkedIn", postedDaysAgo: 0, salaryRange: "6–10 LPA", applyUrl: "https://flipkart.jobs/backend-dev", description: "Flipkart seeks junior backend developers to build scalable APIs for our e-commerce platform. Work with Python/Django stack, handle millions of transactions daily. Join our growing infrastructure team. Based in Sarjapur." },
  { id: 4, title: "Frontend Intern", company: "Swiggy", location: "Bangalore", mode: "Remote", experience: "Fresher", skills: ["React", "JavaScript", "CSS", "HTML"], source: "LinkedIn", postedDaysAgo: 3, salaryRange: "₹15k–₹25k/month Internship", applyUrl: "https://swiggy.jobs/intern-frontend", description: "Join Swiggy's frontend team as an intern and build user-facing features for millions of users. Work with React and modern web technologies. Fully remote role with flexible hours. Learn from senior engineers." },
  { id: 5, title: "QA Intern", company: "Razorpay", location: "Bangalore", mode: "Onsite", experience: "Fresher", skills: ["Test Automation", "Selenium", "Python"], source: "Indeed", postedDaysAgo: 4, salaryRange: "₹18k–₹28k/month Internship", applyUrl: "https://razorpay.com/careers/qa-intern", description: "Razorpay is hiring QA interns for our payments platform. You'll write test cases, automate tests, and ensure product quality. Work with Python and Selenium. Great exposure to fintech. Located in Koramangala." },
  { id: 6, title: "Data Analyst Intern", company: "PhonePe", location: "Bangalore", mode: "Hybrid", experience: "Fresher", skills: ["SQL", "Python", "Data Analysis", "Tableau"], source: "LinkedIn", postedDaysAgo: 2, salaryRange: "₹22k–₹32k/month Internship", applyUrl: "https://phonpe.careers/internship", description: "PhonePe is looking for data analyst interns to work on payment analytics. Build dashboards, analyze user behavior, and drive insights. Work with SQL, Python, and Tableau. Hybrid role in Bangalore." },
  { id: 7, title: "Java Developer (0-1 years)", company: "Cognizant", location: "Pune", mode: "Onsite", experience: "0-1", skills: ["Java", "Spring Boot", "Microservices"], source: "Naukri", postedDaysAgo: 1, salaryRange: "5–8 LPA", applyUrl: "https://cognizant.com/careers/java-dev", description: "Cognizant Pune seeks junior Java developers for enterprise applications. Learn Spring Boot and microservices architecture. Mentorship from senior architects. Located in Baner, Pune." },
  { id: 8, title: "Python Developer (Fresher)", company: "Zoho", location: "Chennai", mode: "Onsite", experience: "Fresher", skills: ["Python", "Django", "MySQL"], source: "LinkedIn", postedDaysAgo: 5, salaryRange: "4–6 LPA", applyUrl: "https://zoho.com/careers/python-dev", description: "Zoho in Chennai is hiring fresher Python developers for our product teams. Work with Django and MySQL. Build features used by millions. Great learning environment with flat hierarchy." },
  { id: 9, title: "React Developer (1-3 years)", company: "Freshworks", location: "Bangalore", mode: "Remote", experience: "1-3", skills: ["React", "JavaScript", "Redux", "Webpack"], source: "LinkedIn", postedDaysAgo: 2, salaryRange: "10–15 LPA", applyUrl: "https://freshworks.com/careers/react", description: "Freshworks is building the next generation of customer engagement software. We need React developers with 1-3 years experience. Fully remote, global team, modern tech stack." },
  { id: 10, title: "Full Stack Developer", company: "CRED", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["React", "Node.js", "MongoDB", "AWS"], source: "LinkedIn", postedDaysAgo: 0, salaryRange: "12–18 LPA", applyUrl: "https://cred.club/careers/fullstack", description: "CRED is disrupting credit card management. Build full-stack features with React and Node.js. Work on fintech products used by millions. Hybrid at Whitefield, Bangalore." },
  { id: 11, title: "DevOps Engineer", company: "Juspay", location: "Bangalore", mode: "Onsite", experience: "0-1", skills: ["Kubernetes", "Docker", "AWS", "CI/CD"], source: "LinkedIn", postedDaysAgo: 3, salaryRange: "7–11 LPA", applyUrl: "https://juspay.com/careers/devops", description: "Juspay is India's leading payment gateway. We're hiring DevOps engineers to manage cloud infrastructure. Work with Kubernetes, Docker, and AWS. Growth opportunity in fintech." },
  { id: 12, title: "Senior Backend Engineer", company: "Paytm", location: "Noida", mode: "Onsite", experience: "3-5", skills: ["Java", "Microservices", "Kafka", "MongoDB"], source: "Naukri", postedDaysAgo: 4, salaryRange: "15–25 LPA", applyUrl: "https://paytm.com/careers/backend", description: "Paytm is hiring senior backend engineers for our digital wallet platform. Build scalable microservices handling billions of transactions. Tech lead opportunities available." },
  { id: 13, title: "Machine Learning Engineer", company: "Amazon", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["Python", "TensorFlow", "AWS", "SQL"], source: "LinkedIn", postedDaysAgo: 1, salaryRange: "13–20 LPA", applyUrl: "https://amazon.jobs/ml-engineer", description: "Amazon is building ML solutions for e-commerce. Work on recommendation systems and computer vision. Use TensorFlow and AWS SageMaker. Join our AI research team in Bangalore." },
  { id: 14, title: "Frontend Engineer (1-3 years)", company: "Flipkart", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["React", "TypeScript", "Redux", "Testing"], source: "LinkedIn", postedDaysAgo: 2, salaryRange: "11–16 LPA", applyUrl: "https://flipkart.jobs/frontend-eng", description: "Flipkart seeks experienced frontend engineers for our web platform. Build high-performance React apps for millions of users. Work on mobile-first responsive design." },
  { id: 15, title: "QA Automation Engineer", company: "Accenture", location: "Pune", mode: "Onsite", experience: "0-1", skills: ["Selenium", "Java", "TestNG", "Cucumber"], source: "Naukri", postedDaysAgo: 5, salaryRange: "5–8 LPA", applyUrl: "https://accenture.com/careers/qa-automation", description: "Accenture Pune is looking for QA automation engineers. Work on large enterprise projects, build automated test suites. Excellent learning curve with global exposure." },
  { id: 16, title: "Cloud Solutions Architect", company: "IBM", location: "Bangalore", mode: "Hybrid", experience: "3-5", skills: ["Cloud Architecture", "AWS", "Azure", "Terraform"], source: "LinkedIn", postedDaysAgo: 3, salaryRange: "18–28 LPA", applyUrl: "https://ibm.com/careers/cloud-arch", description: "IBM is hiring cloud architects for enterprise solutions. Design scalable cloud infrastructure, lead technical teams. Work with AWS and Azure. Bangalore-based hybrid role." },
  { id: 17, title: "Database Administrator", company: "Oracle", location: "Bangalore", mode: "Onsite", experience: "1-3", skills: ["Oracle DB", "SQL", "Performance Tuning", "Backup"], source: "LinkedIn", postedDaysAgo: 4, salaryRange: "10–15 LPA", applyUrl: "https://oracle.com/careers/dba", description: "Oracle India is seeking database administrators. Manage large-scale Oracle databases, optimize performance. Work with enterprise clients. Located in Bangalore." },
  { id: 18, title: "Java Backend Engineer", company: "Capgemini", location: "Mumbai", mode: "Hybrid", experience: "1-3", skills: ["Java", "Spring", "Hibernate", "PostgreSQL"], source: "Naukri", postedDaysAgo: 0, salaryRange: "9–14 LPA", applyUrl: "https://capgemini.com/careers/java", description: "Capgemini Mumbai seeks Java backend engineers for digital transformation projects. Work with Spring framework, build enterprise applications. Hybrid role in BKC area." },
  { id: 19, title: "UI/UX Designer", company: "Swiggy", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["Figma", "User Research", "Prototyping", "Design Systems"], source: "LinkedIn", postedDaysAgo: 2, salaryRange: "8–13 LPA", applyUrl: "https://swiggy.jobs/designer", description: "Swiggy is building delightful user experiences. We need UI/UX designers to design food delivery interfaces. Work with Figma, collaborate with engineers and product teams." },
  { id: 20, title: "Data Engineer", company: "Flipkart", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["Spark", "Hadoop", "SQL", "Python", "AWS"], source: "LinkedIn", postedDaysAgo: 3, salaryRange: "12–18 LPA", applyUrl: "https://flipkart.jobs/data-engineer", description: "Flipkart's data team processes terabytes of data daily. Build data pipelines with Spark and Hadoop. Work on analytics and ML infrastructure." },
  { id: 21, title: "SDE Intern (Remote)", company: "Razorpay", location: "Remote", mode: "Remote", experience: "Fresher", skills: ["Go", "JavaScript", "APIs", "Testing"], source: "LinkedIn", postedDaysAgo: 1, salaryRange: "₹25k–₹35k/month Internship", applyUrl: "https://razorpay.com/careers/sde-intern", description: "Razorpay is hiring remote SDE interns. Build backend services in Go, work on payment systems. Fully remote, flexible timing, great for freshers to learn." },
  { id: 22, title: "Android Developer", company: "Paytm", location: "Noida", mode: "Onsite", experience: "1-3", skills: ["Kotlin", "Android", "MVVM", "Firebase"], source: "Naukri", postedDaysAgo: 4, salaryRange: "9–14 LPA", applyUrl: "https://paytm.com/careers/android", description: "Paytm is building best-in-class mobile apps. We need Android developers with Kotlin expertise. Build features for 500M+ users. Located in Noida." },
  { id: 23, title: "iOS Developer", company: "CRED", location: "Bangalore", mode: "Hybrid", experience: "0-1", skills: ["Swift", "iOS", "UIKit", "Xcode"], source: "LinkedIn", postedDaysAgo: 2, salaryRange: "8–12 LPA", applyUrl: "https://cred.club/careers/ios", description: "CRED is looking for iOS developers to build our credit card app. Work with Swift and modern iOS tools. Join our mobile-first fintech company." },
  { id: 24, title: "API Intern", company: "PhonePe", location: "Bangalore", mode: "Hybrid", experience: "Fresher", skills: ["REST APIs", "Node.js", "PostgreSQL", "Postman"], source: "LinkedIn", postedDaysAgo: 0, salaryRange: "₹20k–₹30k/month Internship", applyUrl: "https://phonpe.careers/api-intern", description: "PhonePe is hiring API interns to build backend services. Learn about REST APIs, work with Node.js and PostgreSQL. Hybrid role with mentorship." },
  { id: 25, title: "Security Engineer", company: "Juspay", location: "Bangalore", mode: "Onsite", experience: "1-3", skills: ["Security Auditing", "Penetration Testing", "Compliance", "Cryptography"], source: "LinkedIn", postedDaysAgo: 5, salaryRange: "11–16 LPA", applyUrl: "https://juspay.com/careers/security", description: "Juspay is protecting payment transactions. We need security engineers for vulnerability assessment. Work with fintech security, penetration testing, compliance." },
  { id: 26, title: "Product Manager", company: "Amazon", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["Product Strategy", "Data Analysis", "User Research", "Leadership"], source: "LinkedIn", postedDaysAgo: 2, salaryRange: "14–22 LPA", applyUrl: "https://amazon.jobs/pm", description: "Amazon India is seeking product managers for Alexa. Lead cross-functional teams, define product strategy. Work on AI products used by millions." },
  { id: 27, title: "Business Analyst", company: "TCS", location: "Mumbai", mode: "Onsite", experience: "0-1", skills: ["Requirements Analysis", "SQL", "Agile", "Documentation"], source: "Naukri", postedDaysAgo: 3, salaryRange: "5–8 LPA", applyUrl: "https://tcs.com/careers/ba", description: "TCS Mumbai is hiring business analysts for digital transformation. Work with clients to gather requirements, design solutions. Learn industry practices." },
  { id: 28, title: "Solutions Architect", company: "SAP", location: "Bangalore", mode: "Hybrid", experience: "3-5", skills: ["SAP ABAP", "Enterprise Solutions", "BAPI", "OOP"], source: "LinkedIn", postedDaysAgo: 4, salaryRange: "16–24 LPA", applyUrl: "https://sap.com/careers/architect", description: "SAP is hiring solutions architects for ERP implementations. Design enterprise systems, lead customer projects. Work with enterprise clients across industries." },
  { id: 29, title: "Graphic Designer", company: "Freshworks", location: "Bangalore", mode: "Remote", experience: "Fresher", skills: ["Adobe Creative Suite", "Illustrator", "Photoshop", "Design"], source: "LinkedIn", postedDaysAgo: 1, salaryRange: "4–6 LPA", applyUrl: "https://freshworks.com/careers/designer", description: "Freshworks is hiring graphic designers for marketing materials and product design. Work with Adobe tools, create compelling visuals. Remote position." },
  { id: 30, title: "Technical Writer", company: "Dell", location: "Bangalore", mode: "Hybrid", experience: "0-1", skills: ["Technical Documentation", "Markdown", "API Documentation", "Writing"], source: "LinkedIn", postedDaysAgo: 2, salaryRange: "5–8 LPA", applyUrl: "https://dell.com/careers/writer", description: "Dell is looking for technical writers. Document software features, write API guides. Work with engineering teams. Hybrid role in Bangalore." },
  { id: 31, title: "SDE Intern", company: "Flipkart", location: "Bangalore", mode: "Onsite", experience: "Fresher", skills: ["Java", "Data Structures", "System Design"], source: "LinkedIn", postedDaysAgo: 0, salaryRange: "₹25k–₹35k/month Internship", applyUrl: "https://flipkart.jobs/sde-intern", description: "Flipkart is hiring SDE interns for summer internship. Work on e-commerce systems, learn from senior engineers. Onsite in Bangalore." },
  { id: 32, title: "Cybersecurity Analyst", company: "Wipro", location: "Pune", mode: "Onsite", experience: "1-3", skills: ["Cybersecurity", "Threat Analysis", "IDS/IPS", "Firewalls"], source: "Naukri", postedDaysAgo: 3, salaryRange: "8–12 LPA", applyUrl: "https://wipro.com/careers/security", description: "Wipro Pune is hiring cybersecurity analysts. Monitor security threats, manage firewalls. Work on enterprise security projects. Good learning path." },
  { id: 33, title: "Software Engineer", company: "Zoho", location: "Chennai", mode: "Onsite", experience: "1-3", skills: ["Java", "SQL", "Problem Solving", "Agile"], source: "LinkedIn", postedDaysAgo: 4, salaryRange: "8–12 LPA", applyUrl: "https://zoho.com/careers/software-engineer", description: "Zoho is building productivity software. We need software engineers with 1-3 years experience. Work with Java, build features for millions." },
  { id: 34, title: "Cloud Engineer", company: "Amazon", location: "Bangalore", mode: "Hybrid", experience: "0-1", skills: ["AWS", "EC2", "S3", "Lambda", "CloudFormation"], source: "LinkedIn", postedDaysAgo: 1, salaryRange: "7–11 LPA", applyUrl: "https://amazon.jobs/cloud-eng", description: "Amazon Web Services is expanding in India. We're hiring cloud engineers. Work with AWS services, build cloud solutions. Bangalore hybrid role." },
  { id: 35, title: "Marketing Manager", company: "Swiggy", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["Marketing Strategy", "Analytics", "Campaign Management", "Growth"], source: "LinkedIn", postedDaysAgo: 2, salaryRange: "10–15 LPA", applyUrl: "https://swiggy.jobs/marketing", description: "Swiggy is hiring marketing managers for growth initiatives. Build marketing campaigns, analyze metrics. Work on food delivery marketing." },
  { id: 36, title: "HR Analyst", company: "Cognizant", location: "Pune", mode: "Onsite", experience: "Fresher", skills: ["HR Operations", "Recruitment", "Documentation", "Communication"], source: "Naukri", postedDaysAgo: 3, salaryRange: "3–5 LPA", applyUrl: "https://cognizant.com/careers/hr", description: "Cognizant Pune is hiring HR analysts. Support recruitment, handle employee relations. Learn HR operations in IT industry." },
  { id: 37, title: "Finance Analyst", company: "CRED", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["Financial Analysis", "Excel", "SQL", "Analytics"], source: "LinkedIn", postedDaysAgo: 4, salaryRange: "9–13 LPA", applyUrl: "https://cred.club/careers/finance", description: "CRED is hiring finance analysts for our fintech operations. Analyze financial data, build reports. Work with SQL and Excel." },
  { id: 38, title: "Content Writer", company: "Freshworks", location: "Bangalore", mode: "Remote", experience: "Fresher", skills: ["Content Writing", "SEO", "Blogging", "Technical Writing"], source: "LinkedIn", postedDaysAgo: 1, salaryRange: "4–6 LPA", applyUrl: "https://freshworks.com/careers/writer", description: "Freshworks is looking for content writers. Write blog posts, product documentation. Fully remote, work with global teams." },
  { id: 39, title: "Network Engineer", company: "Juspay", location: "Bangalore", mode: "Onsite", experience: "0-1", skills: ["Network Administration", "Cisco", "VPN", "Routing"], source: "LinkedIn", postedDaysAgo: 2, salaryRange: "6–10 LPA", applyUrl: "https://juspay.com/careers/network", description: "Juspay is hiring network engineers. Manage network infrastructure, configure firewalls. Work in fintech network operations." },
  { id: 40, title: "Support Engineer", company: "Oracle", location: "Bangalore", mode: "Onsite", experience: "Fresher", skills: ["Customer Support", "Troubleshooting", "Database", "Communication"], source: "Naukri", postedDaysAgo: 3, salaryRange: "4–6 LPA", applyUrl: "https://oracle.com/careers/support", description: "Oracle is hiring support engineers for product support. Handle customer issues, provide technical support. Great learning curve." },
  { id: 41, title: "Solutions Engineer (1-3 years)", company: "IBM", location: "Pune", mode: "Hybrid", experience: "1-3", skills: ["Solution Design", "Client Management", "Technical Consulting"], source: "LinkedIn", postedDaysAgo: 4, salaryRange: "9–14 LPA", applyUrl: "https://ibm.com/careers/solutions", description: "IBM Pune is hiring solutions engineers. Design solutions for enterprise clients, provide technical consulting. Hybrid role." },
  { id: 42, title: "QA Engineer", company: "PhonePe", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["Test Planning", "Manual Testing", "Automation", "JIRA"], source: "LinkedIn", postedDaysAgo: 0, salaryRange: "7–11 LPA", applyUrl: "https://phonpe.careers/qa", description: "PhonePe is hiring QA engineers for payments testing. Write test cases, perform manual and automated testing. Hybrid role." },
  { id: 43, title: "Growth Analyst", company: "Razorpay", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["Analytics", "Data Science", "Growth Strategy", "SQL"], source: "LinkedIn", postedDaysAgo: 1, salaryRange: "10–15 LPA", applyUrl: "https://razorpay.com/careers/growth", description: "Razorpay is hiring growth analysts. Analyze payment trends, identify growth opportunities. Work with SQL and analytics tools." },
  { id: 44, title: "Backend Developer (Fresher)", company: "Accenture", location: "Bangalore", mode: "Onsite", experience: "Fresher", skills: ["Java", "Spring Boot", "REST APIs", "SQL"], source: "Naukri", postedDaysAgo: 2, salaryRange: "5–8 LPA", applyUrl: "https://accenture.com/careers/backend", description: "Accenture Bangalore is hiring fresher backend developers. Learn Spring Boot, build REST APIs. Join our development team." },
  { id: 45, title: "Frontend Developer (Fresher)", company: "Capgemini", location: "Mumbai", mode: "Onsite", experience: "Fresher", skills: ["React", "JavaScript", "HTML", "CSS"], source: "Naukri", postedDaysAgo: 3, salaryRange: "4–7 LPA", applyUrl: "https://capgemini.com/careers/frontend", description: "Capgemini Mumbai is hiring fresher frontend developers. Learn React, build web applications. Great learning environment." },
  { id: 46, title: "Full Stack Intern", company: "Zoho", location: "Chennai", mode: "Onsite", experience: "Fresher", skills: ["MERN Stack", "JavaScript", "MongoDB", "Node.js"], source: "LinkedIn", postedDaysAgo: 4, salaryRange: "₹18k–₹28k/month Internship", applyUrl: "https://zoho.com/careers/fullstack-intern", description: "Zoho is hiring full stack interns for product development. Work with MERN stack, build web apps. Chennai onsite." },
  { id: 47, title: "Operations Manager", company: "Flipkart", location: "Bangalore", mode: "Onsite", experience: "1-3", skills: ["Operations", "Process Management", "Analytics", "Leadership"], source: "LinkedIn", postedDaysAgo: 2, salaryRange: "8–12 LPA", applyUrl: "https://flipkart.jobs/operations", description: "Flipkart is hiring operations managers for logistics. Manage operations, optimize processes. Work in e-commerce operations." },
  { id: 48, title: "Sales Executive", company: "Paytm", location: "Noida", mode: "Onsite", experience: "Fresher", skills: ["Sales", "Communication", "Negotiation", "CRM"], source: "Naukri", postedDaysAgo: 1, salaryRange: "3–5 LPA", applyUrl: "https://paytm.com/careers/sales", description: "Paytm is hiring sales executives. Sell fintech products, build client relationships. Growth opportunities in sales." },
  { id: 49, title: "Quality Assurance Lead", company: "Amazon", location: "Bangalore", mode: "Hybrid", experience: "3-5", skills: ["QA Strategy", "Test Automation", "Leadership", "Process Improvement"], source: "LinkedIn", postedDaysAgo: 3, salaryRange: "14–20 LPA", applyUrl: "https://amazon.jobs/qa-lead", description: "Amazon is hiring QA leads. Lead QA teams, define testing strategies. Manage quality for large-scale systems." },
  { id: 50, title: "Infrastructure Engineer", company: "CRED", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["Linux", "Docker", "Kubernetes", "Infrastructure"], source: "LinkedIn", postedDaysAgo: 4, salaryRange: "10–15 LPA", applyUrl: "https://cred.club/careers/infra", description: "CRED is building scalable infrastructure. We need engineers for containerization and orchestration. Work with Docker and Kubernetes." },
  { id: 51, title: "System Administrator", company: "Wipro", location: "Hyderabad", mode: "Onsite", experience: "0-1", skills: ["System Administration", "Windows/Linux", "Active Directory", "Networking"], source: "Naukri", postedDaysAgo: 2, salaryRange: "5–8 LPA", applyUrl: "https://wipro.com/careers/sysadmin", description: "Wipro Hyderabad is hiring system administrators. Manage IT infrastructure, support users. Learn enterprise IT operations." },
  { id: 52, title: "Embedded Systems Engineer", company: "Dell", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["C/C++", "Embedded Systems", "Hardware", "RTOS"], source: "LinkedIn", postedDaysAgo: 0, salaryRange: "9–14 LPA", applyUrl: "https://dell.com/careers/embedded", description: "Dell is hiring embedded systems engineers. Work on hardware-software integration. Build embedded systems for Dell products." },
  { id: 53, title: "Integration Specialist", company: "SAP", location: "Bangalore", mode: "Hybrid", experience: "0-1", skills: ["Integration", "ABAP", "APIs", "Middleware"], source: "LinkedIn", postedDaysAgo: 1, salaryRange: "6–10 LPA", applyUrl: "https://sap.com/careers/integration", description: "SAP is hiring integration specialists. Work on system integrations, build APIs. Learn enterprise integration patterns." },
  { id: 54, title: "Research Scientist", company: "Amazon", location: "Bangalore", mode: "Hybrid", experience: "3-5", skills: ["Machine Learning", "Research", "Python", "Publication"], source: "LinkedIn", postedDaysAgo: 2, salaryRange: "20–35 LPA", applyUrl: "https://amazon.jobs/research", description: "Amazon's AI Lab is hiring research scientists. Conduct research in ML, publish papers. Work on cutting-edge AI projects." },
  { id: 55, title: "Engineering Manager", company: "Flipkart", location: "Bangalore", mode: "Hybrid", experience: "3-5", skills: ["Leadership", "Team Management", "Technical Depth", "Mentoring"], source: "LinkedIn", postedDaysAgo: 3, salaryRange: "16–25 LPA", applyUrl: "https://flipkart.jobs/eng-manager", description: "Flipkart is hiring engineering managers. Lead engineering teams, mentor engineers. Hybrid at Bangalore." },
  { id: 56, title: "Documentation Specialist", company: "Freshworks", location: "Bangalore", mode: "Remote", experience: "Fresher", skills: ["Technical Documentation", "Software Usage", "Knowledge Base", "Writing"], source: "LinkedIn", postedDaysAgo: 4, salaryRange: "4–6 LPA", applyUrl: "https://freshworks.com/careers/docs", description: "Freshworks is hiring documentation specialists. Create knowledge bases, write guides. Remote position, learning opportunity." },
  { id: 57, title: "Innovation Consultant", company: "Cognizant", location: "Pune", mode: "Hybrid", experience: "1-3", skills: ["Innovation", "Consulting", "Problem Solving", "Business Analysis"], source: "LinkedIn", postedDaysAgo: 1, salaryRange: "9–13 LPA", applyUrl: "https://cognizant.com/careers/innovation", description: "Cognizant is hiring innovation consultants. Help clients transform digitally. Work on emerging technologies." },
  { id: 58, title: "Testing Lead", company: "TCS", location: "Mumbai", mode: "Onsite", experience: "1-3", skills: ["Test Management", "JIRA", "Automation", "Team Leadership"], source: "Naukri", postedDaysAgo: 2, salaryRange: "8–12 LPA", applyUrl: "https://tcs.com/careers/test-lead", description: "TCS Mumbai is hiring testing leads. Manage test teams, define testing strategies. Work on large enterprise projects." },
  { id: 59, title: "Customer Success Manager", company: "Zoho", location: "Chennai", mode: "Hybrid", experience: "Fresher", skills: ["Customer Support", "Communication", "Product Knowledge", "CRM"], source: "LinkedIn", postedDaysAgo: 3, salaryRange: "5–8 LPA", applyUrl: "https://zoho.com/careers/csm", description: "Zoho is hiring customer success managers. Support customers, ensure satisfaction. Build long-term relationships." },
  { id: 60, title: "Compliance Officer", company: "Juspay", location: "Bangalore", mode: "Onsite", experience: "1-3", skills: ["Compliance", "Regulations", "Auditing", "Documentation"], source: "LinkedIn", postedDaysAgo: 4, salaryRange: "9–13 LPA", applyUrl: "https://juspay.com/careers/compliance", description: "Juspay is hiring compliance officers. Ensure regulatory compliance, manage audits. Work in fintech compliance." },
];

export const ALL_LOCATIONS = [...new Set(jobsDataset.map(j => j.location))].sort();
export const ALL_MODES = ["Remote", "Hybrid", "Onsite"];
export const ALL_EXPERIENCES = [...new Set(jobsDataset.map(j => j.experience))];
export const ALL_SOURCES = [...new Set(jobsDataset.map(j => j.source))].sort();
